print("==============================")
print("     AGE CALCULATOR           ")
print("==============================")
print()
name = input("What is your name?")
age = int(input("How old are you?"))
year = int(input("What year is it?"))

print()
print("Hello ",name+"!")
print()
print()
print("You were born around: ",year-age)
print("Next year you will be: ",age+1)
print("In 10 years you will be: ",age+10)
print()
print()
print("You have been alive for approximately", age*12 ,"months!")
print("=====================================")